INSERT INTO TARIFA (MODALIDAD,VALOR,TIPO_VEHICULO) VALUES('HORA',1000,'CARRO');
INSERT INTO TARIFA (MODALIDAD,VALOR,TIPO_VEHICULO) VALUES('HORA',500,'MOTO');
INSERT INTO TARIFA (MODALIDAD,VALOR,TIPO_VEHICULO) VALUES('DIA',8000,'CARRO');
INSERT INTO TARIFA (MODALIDAD,VALOR,TIPO_VEHICULO) VALUES('DIA',4000,'MOTO');


